CREATE TABLE product(
	ID SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	price DECIMAl(10,2) NOT NULL,
	image_url VARCHAR(255) NOT NULL,
	category VARCHAR(255) NOT NULL,
	tags VARCHAR (255) not null
);



CREATE TABLE sale(
	ID SERIAL PRIMARY KEY,
	finalPrice DECIMAL(10,2) NOT NULL
)