import type { Metadata } from 'next';
import './globals.css';
import { HeaderPage } from '../components/HeaderPage';
import { CartProvider } from '../context/ContextCart';
import { Funnel_Display, Plaster } from 'next/font/google';

const funnelDisplay = Funnel_Display({
  subsets: ['latin'],
  weight: ['300','400','500','600','700','800'],
    variable: '--font-funnel-display',
});

const plaster = Plaster({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-plaster',
});


export const metadata: Metadata = {
  title: 'Urban Shop',
  description: 'Generated by create next app',
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${plaster.variable} ${funnelDisplay.className} antialiased`}
      >
        <CartProvider>
          <HeaderPage />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
